### ISSUE TITLE
Did you miss hammerspoon?

### ISSUE THREAD

**Issue by KoljaL** [tborychowski/awesome-mac#1]
After i saw your list, I can neither imaging, that you don't know hammerspoon.org, nor that you don't find it useful.

**Comment by tborychowski** [comment]
Hi,

Thanks for your comment.
Yes, I know it, but somehow I've never felt a need for any of the features it offers.
(similarly to BetterTouchTool that everyone seems to praise, but I fail to find even 1 thing that would be useful to me).

I also don't "speak" lua :-)

Can you give me 1 or 2 examples of the most useful thing it does for you?
